// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4jGkkT3xnL1Z-JFl9pBESvhqNNOe3ts',
    appId: '1:191108163533:web:b633254037e863eeff4684',
    messagingSenderId: '191108163533',
    projectId: 'record-project-828af',
    authDomain: 'record-project-828af.firebaseapp.com',
    storageBucket: 'record-project-828af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZH1S40HRbvmbe6gdBwUpUBy5XDqk41i8',
    appId: '1:191108163533:android:a53b4e1dd48879b6ff4684',
    messagingSenderId: '191108163533',
    projectId: 'record-project-828af',
    storageBucket: 'record-project-828af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3_S15BJZdWuAXslisSgaCgqNZYrVcoY',
    appId: '1:191108163533:ios:703c9c091261cdadff4684',
    messagingSenderId: '191108163533',
    projectId: 'record-project-828af',
    storageBucket: 'record-project-828af.appspot.com',
    iosBundleId: 'com.example.recordProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR3_S15BJZdWuAXslisSgaCgqNZYrVcoY',
    appId: '1:191108163533:ios:703c9c091261cdadff4684',
    messagingSenderId: '191108163533',
    projectId: 'record-project-828af',
    storageBucket: 'record-project-828af.appspot.com',
    iosBundleId: 'com.example.recordProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4jGkkT3xnL1Z-JFl9pBESvhqNNOe3ts',
    appId: '1:191108163533:web:0b4b506e0cdfa106ff4684',
    messagingSenderId: '191108163533',
    projectId: 'record-project-828af',
    authDomain: 'record-project-828af.firebaseapp.com',
    storageBucket: 'record-project-828af.appspot.com',
  );
}
